#!/bin/bash

for i in $(ls ~/Virtual\ Machines.localized/rhce* | grep .vmx$ | cut -d '.' -f 1)
do 
    vmrun revertToSnapshot ~/Virtual\ Machines.localized/$i.vmwarevm/$i.vmx Snapshot
    vmrun start ~/Virtual\ Machines.localized/$i.vmwarevm/$i.vmx nogui
done

sleep 5 

# lets assume you have the control node in your hosts file
ssh ansible@control

